kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    requirepass ""
    maxmemory 100mb
    maxmemory-policy noeviction 
    appendonly yes
    appendfsync everysec
    loglevel notice
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    cluster-enabled no
    daemonize no
