# This dockerfile can be used in production
FROM node:20 AS build
WORKDIR /src
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
COPY --from=build /src/dist /usr/share/nginx/html
