environment: dev
logger_output: stdout

http_service:
  host: http_service
  port: 8080

websocket_service:
  host: websocket_service
  port: 8080

auth_service:
  resolve_srv: false
  host: auth_service
  port: 50051

  repository:
    driver: redis
    redis_config:
      host: redis
      port: 6379

matchmaking_service:
  resolve_srv: false
  host: matchmaking_service
  port: 50051

  repository:
    driver: redis
    redis_config:
      host: redis
      port: 6379

game_service:
  resolve_srv: false
  host: game_service
  port: 50051

collector:
  enable_metric_provider: true
  host: collector
  port: 4317
