environment: prod
graceful_shutdown: true
logger_output: stdout

http_service:
  host: localhost
  port: 8081

websocket_service:
  host: localhost
  port: 8082

auth_service:
  host: localhost
  port: 50052

auth_repository:
  driver: redis
  redis_config:
    host: localhost
    port: 6379

matchmaking_service:
  host: localhost
  port: 50053

matchmaking_repository:
  driver: redis
  redis_config:
    host: localhost
    port: 6379

game_service:
  host: localhost
  port: 50054

collector:
  enable_metric_provider: true
  host: localhost
  port: 4317
