# This dockerfile can be used in production
FROM golang:1.22.8 AS build
WORKDIR /src
COPY ./go.mod ./go.sum /src
RUN go mod download
COPY ./ /src
ARG ENTRY_PKG=./cmd/http_service
RUN go build -o /bin/server ${ENTRY_PKG}

FROM ubuntu:22.04
COPY --from=build /bin/server /app/server
COPY --from=build /src/config.example.yaml /app/config.yaml
WORKDIR /app
