FROM golang:1.22.8 AS build
WORKDIR /src
COPY ./go.mod ./go.sum /src
RUN go mod download
COPY ./ /src
RUN go build -o /bin/server ./cmd/main

FROM ubuntu:22.04
COPY --from=build /bin/server /app/server
WORKDIR /app
