apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: xenoblast
    service: collector
  type: ClusterIP
  ports:
    - name: exporter
      port: 8889
      targetPort: 8889
    - name: grpc-receiver
      port: 4317
      targetPort: 4317
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
spec:
  selector:
    matchLabels:
      app: xenoblast
      service: collector
  template:
    metadata:
      labels:
        app: xenoblast
        service: collector
    spec:
      containers:
        - name: collector
          image: otel/opentelemetry-collector-contrib:0.116.1
          ports:
            - name: exporter
              containerPort: 8889
            - name: grpc-receiver
              containerPort: 4317
            - containerPort: 55679
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
