apiVersion: v1
kind: Service
metadata:
  name: frontend-assets
spec:
  selector:
    app: xenoblast
    service: frontend-assets
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-assets
  labels:
    app: xenoblast
    service: frontend-assets
spec:
  selector:
    matchLabels:
      app: xenoblast
      service: frontend-assets
  replicas: 1
  template:
    metadata:
      labels:
        app: xenoblast
        service: frontend-assets
        group: ingress-target
    spec:
      containers:
        - name: webserver
          image: xenoblast-frontend-assets:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
---

