name: Deploy to ECS

permissions:
  id-token: write

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      aws-role-arn:
        required: true
        type: string
      taskdef-arn:
        required: true
        type: string
      container-name:
        required: true
        type: string
      cluster-name:
        required: true
        type: string
      service-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role-arn }}

      # https://github.com/aws-actions/amazon-ecs-render-task-definition
      - id: fill-image
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn: ${{ inputs.taskdef-arn }}
          container-name: ${{ inputs.container-name }}
          image: ${{ inputs.image-tag }}

      # https://github.com/aws-actions/amazon-ecs-deploy-task-definition
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.fill-image.outputs.task-definition }}
          cluster: ${{ inputs.cluster-name }}
          service: ${{ inputs.service-name }}
