name: xenoblast-development

services:
  api_gateway:
    build:
      context: ../../api-gateway
      dockerfile: dockerfile
    volumes:
      - ../../api-gateway/nginx.dev.conf:/etc/nginx/nginx.conf
      - ../../api-gateway/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend_dev
      - http_service
      - websocket_service

  frontend_dev:
    build:
      context: ../../frontend
      dockerfile: dockerfile.dev
    volumes:
      - ../../frontend:/src
    command: ["dev"]
    expose:
      - 8080

  http_service:
    build:
      context: ../../backend
      dockerfile: dockerfile.dev
    volumes:
      - ../../backend:/src
    command: -service http
    expose:
      - 8080
    depends_on:
      - collector

  websocket_service:
    build:
      context: ../../backend
      dockerfile: dockerfile.dev
    volumes:
      - ../../backend:/src
    command: -service websocket
    expose:
      - 8080
    depends_on:
      - collector

  auth_service:
    build:
      context: ../../backend
      dockerfile: dockerfile.dev
    volumes:
      - ../../backend:/src
    command: -service auth
    expose:
      - 50051
    depends_on:
      - redis
      - collector

  matchmaking_service:
    build:
      context: ../../backend
      dockerfile: dockerfile.dev
    volumes:
      - ../../backend:/src
    command: -service matchmaking
    expose:
      - 50051
    depends_on:
      - redis
      - collector

  game_service:
    build:
      context: ../../backend
      dockerfile: dockerfile.dev
    volumes:
      - ../../backend:/src
    command: -service game
    expose:
      - 50051
    deploy:
      mode: replicated
      replicas: 1 # This value can be increased to simulate scaling out.
      endpoint_mode: dnsrr
    depends_on:
      - collector

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis_data:/data

  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.112.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../../monitoring/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    expose:
      - 8889 # Prometheus exporter metrics
      - 4317 # grpc receiver
      - 55679
    depends_on:
      - prometheus

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus #persistence
      - ../../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090

volumes:
  redis_data:
  prometheus_data:
