services:
  api_gateway:
    image: nginx:latest
    volumes:
      - ../../api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ../../api-gateway/conf.d/:/etc/nginx/conf.d/
      - ../../api-gateway/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80

  http_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    volumes:
      - ../../backend:/src
    command: ${SERVER_CMD_BASE} -service http
    expose:
      - 8080

  websocket_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    volumes:
      - ../../backend:/src
    command: ${SERVER_CMD_BASE} -service websocket
    expose:
      - 8080

  auth_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    volumes:
      - ../../backend:/src
    command: ${SERVER_CMD_BASE} -service auth
    expose:
      - 50051

  matchmaking_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    volumes:
      - ../../backend:/src
    command: ${SERVER_CMD_BASE} -service matchmaking
    expose:
      - 50051

  game_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    volumes:
      - ../../backend:/src
    command: ${SERVER_CMD_BASE} -service game
    expose:
      - 50051
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis_data:/data

  collector:
    image: otel/opentelemetry-collector-contrib:0.112.0
    container_name: collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../../monitoring/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    expose:
      - 8889 # Prometheus exporter metrics
      - 4317 # grpc receiver
      - 55679

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus #persistence
      - ../../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana #persistence
      - ../../monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ../../monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}

volumes:
  redis_data:
  prometheus_data:
  grafana_data:
