services:
  api_gateway:
    image: nginx:latest
    volumes:
      - ../../api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ../../api-gateway/conf.d/:/etc/nginx/conf.d/
      - ../../api-gateway/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80

  http_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    command: ${SERVER_CMD_BASE} -service http
    expose:
      - 8080

  websocket_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    command: ${SERVER_CMD_BASE} -service websocket
    expose:
      - 8080

  auth_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    command: ${SERVER_CMD_BASE} -service auth
    expose:
      - 50051

  matchmaking_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    command: ${SERVER_CMD_BASE} -service matchmaking
    expose:
      - 50051

  game_service:
    env_file: .env
    build:
      context: ../../backend
      dockerfile: ${SERVER_DOCKER_FILE}
    command: ${SERVER_CMD_BASE} -service game
    expose:
      - 50051
