name: Build and Push Auth Service to ECR

permissions:
  id-token: write

on:
  push:
    branches:
      - refactor/microservice
    # branches:
    #   - testing
    #   - production
    # paths:
    #   - backend/cmd/auth_service/**
    #   - backend/internal/service/auth_service/**
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      ECS_AUTH_TASKDEF_ARN:
        required: true

env:
  AWS_REGION: ap-east-1
  ECR_AUTH_REPO_NAME: xenoblast-auth-service
  ECS_AUTH_CONTAINER_NAME: auth_service
  ECS_CLUSTER_NAME: xenoblast
  ECS_AUTH_SERVICE_NAME: xenoblast-auth_service

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al /home/runner/work/xenoblast/xenoblast/
      - uses: actions/checkout@v4

  test:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - id: build
        uses: ./.github/actions/build_tag_push
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          repo-name: ${{ env.ECR_AUTH_REPO_NAME }}
          before-build-script: |
            cd backend/
          build-args: --build-arg ENTRY_PKG=./cmd/auth_service
    outputs:
      image: ${{ steps.build.outputs.image }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/deploy
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          taskdef-arn: ${{ secrets.ECS_AUTH_TASKDEF_ARN }}
          container-name: ${{ env.ECS_AUTH_CONTAINER_NAME }}
          image: ${{ needs.build.outputs.image }}
          cluster-name: ${{ env.ECS_CLUSTER_NAME }}
          service-name: ${{ env.ECS_AUTH_SERVICE_NAME }}
