name: Build and Push API Gateway Related Services to ECR

permissions:
  id-token: write

on:
  # push:
  #   branches:
  #     - refactor/microservice
  # branches:
  #   - testing
  #   - production
  # paths:
  #   - api-gateway/**
  #   - backend/cmd/http_service/**
  #   - backend/internal/service/http_service/**
  #   - backend/cmd/websocket_service/**
  #   - backend/internal/service/websocket_service/**
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      ECS_BACKEND_TASKDEF_ARN:
        required: true

env:
  AWS_REGION: ap-east-1
  ECR_API_GATEWAY_REPO_NAME: xenoblast-api-gateway
  ECR_HTTP_SERVICE_REPO_NAME: xenoblast-http-service
  ECR_WEBSOCKET_SERVICE_REPO_NAME: xenoblast-websocket-service
  ECS_API_GATEWAY_CONTAINER_NAME: api_gateway
  ECS_HTTP_CONTAINER_NAME: http_service
  ECS_WEBSOCKET_CONTAINER_NAME: websocket_service
  ECS_CLUSTER_NAME: xenoblast
  ECS_BACKEND_SERVICE_NAME: xenoblast-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: build-api-gateway
        uses: ./.github/actions/build_tag_push
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          repo-name: ${{ env.ECR_API_GATEWAY_REPO_NAME }}
          before-build-script: |
            cd frontend
            docker build -t frontend:latest .
            cd -
            cd api-gateway
          build-args: --build-arg ASSET_IMAGE=frontend:latest --build-arg ASSET_PATH=/etc/nginx/html

      - id: build-http
        uses: ./.github/actions/build_tag_push
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          repo-name: ${{ env.ECR_HTTP_SERVICE_REPO_NAME }}
          before-build-script: |
            cd backend/
          build-args: --build-arg ENTRY_PKG=./cmd/http_service

      - id: build-websocket
        uses: ./.github/actions/build_tag_push
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          repo-name: ${{ env.ECR_WEBSOCKET_SERVICE_REPO_NAME }}
          before-build-script: |
            cd backend/
          build-args: --build-arg ENTRY_PKG=./cmd/websocket_service

    outputs:
      api_gateway_image: ${{ steps.build-api-gateway.outputs.image }}
      http_image: ${{ steps.build-http.outputs.image }}
      websocket_image: ${{ steps.build-websocket.outputs.image }}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          taskdef-arn: ${{ secrets.ECS_BACKEND_TASKDEF_ARN }}
          container-name: ${{ env.ECS_API_GATEWAY_CONTAINER_NAME }}
          image: ${{ needs.build.outputs.api_gateway_image }}
          cluster-name: ${{ env.ECS_CLUSTER_NAME }}
          service-name: ${{ env.ECS_BACKEND_SERVICE_NAME }}

      - uses: ./.github/actions/deploy
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          taskdef-arn: ${{ secrets.ECS_BACKEND_TASKDEF_ARN }}
          container-name: ${{ env.ECS_HTTP_CONTAINER_NAME }}
          image: ${{ needs.build.outputs.http_image }}
          cluster-name: ${{ env.ECS_CLUSTER_NAME }}
          service-name: ${{ env.ECS_BACKEND_SERVICE_NAME }}

      - uses: ./.github/actions/deploy
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          taskdef-arn: ${{ secrets.ECS_BACKEND_TASKDEF_ARN }}
          container-name: ${{ env.ECS_WEBSOCKET_CONTAINER_NAME }}
          image: ${{ needs.build.outputs.websocket_image }}
          cluster-name: ${{ env.ECS_CLUSTER_NAME }}
          service-name: ${{ env.ECS_BACKEND_SERVICE_NAME }}
