name: Deploy Matchmaking Service

permissions:
  id-token: write

on:
  push:
    branches:
      - testing
      - production
    paths:
      - backend/dockerfile
      - backend/go.sum
      - backend/cmd/matchmaking_service/**
      - backend/internal/service/matchmaking_service/**
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      ECS_MATCHMAKING_TASKDEF_ARN:
        required: true

env:
  AWS_REGION: ap-east-1
  ECR_MATCHMAKING_REPO_NAME: xenoblast-matchmaking-service
  ECS_MATCHMAKING_CONTAINER_NAME: matchmaking_service
  ECS_CLUSTER_NAME: xenoblast
  ECS_MATCHMAKING_SERVICE_NAME: xenoblast-matchmaking_service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: build
        uses: ./.github/actions/build_tag_push
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          repo-name: ${{ env.ECR_MATCHMAKING_REPO_NAME }}
          before-build-script: |
            cd backend/
          build-args: --build-arg ENTRY_PKG=./cmd/matchmaking_service
    outputs:
      image: ${{ steps.build.outputs.image }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          taskdef-arn: ${{ secrets.ECS_MATCHMAKING_TASKDEF_ARN }}
          container-name: ${{ env.ECS_MATCHMAKING_CONTAINER_NAME }}
          image: ${{ needs.build.outputs.image }}
          cluster-name: ${{ env.ECS_CLUSTER_NAME }}
          service-name: ${{ env.ECS_MATCHMAKING_SERVICE_NAME }}
