name: Build and Push Matchmaking Service to ECR

permissions:
  id-token: write

on:
  push:
    branches:
      - refactor/microservice
    # branches:
    #   - testing
    #   - production
    # paths:
    #   - backend/cmd/matchmaking_service/**
    #   - backend/internal/service/matchmaking_service/**
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: true
      ECS_MATCHMAKING_TASKDEF_ARN:
        required: true

env:
  AWS_REGION: ap-east-1
  ECR_MATCHMAKING_REPO_NAME: xenoblast-matchmaking-service
  ECS_MATCHMAKING_CONTAINER_NAME: matchmaking_service
  ECS_CLUSTER_NAME: xenoblast
  ECS_MATCHMAKING_SERVICE_NAME: xenoblast-matchmaking_service

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: test
        uses: ./.github/actions/test

      - id: build-tag-push
        uses: ./.github/actions/build_tag_push
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          repo-name: ${{ env.ECR_MATCHMAKING_REPO_NAME }}
          before-build-script: |
            cd backend/
          build-args: --build-arg ENTRY_PKG=./cmd/matchmaking_service

      - id: deploy
        uses: ./.github/actions/deploy
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          taskdef-arn: ${{ secrets.ECS_MATCHMAKING_TASKDEF_ARN }}
          container-name: ${{ env.ECS_MATCHMAKING_CONTAINER_NAME }}
          image: ${{ steps.build-tag-push.outputs.image }}
          cluster-name: ${{ env.ECS_CLUSTER_NAME }}
          service-name: ${{ env.ECS_MATCHMAKING_SERVICE_NAME }}
