name: Build and Push to ECR

permissions:
  id-token: write

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#login-to-amazon-ecr-private-then-build-and-push-a-docker-image
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build -t frontend:latest .
          cd -
          cd api-gateway
          docker build -t $REGISTRY/xenoblast-api-gateway:$IMAGE_TAG .
          docker push $REGISTRY/xenoblast-api-gateway:$IMAGE_TAG
          cd -
          cd backend
          docker build -t $REGISTRY/xenoblast-backend:$IMAGE_TAG .
          docker push $REGISTRY/xenoblast-backend:$IMAGE_TAG
          cd -
