name: Build and Push to ECR

permissions:
  id-token: write

on:
  push:
    branches:
      - feature/deploy

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache-dependency-path: backend/go.sum
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go mod download
      - name: Test with the Go CLI
        run: go test ./...

  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # https://github.com/aws-actions/amazon-ecr-login?tab=readme-ov-file#login-to-amazon-ecr-private-then-build-and-push-a-docker-image
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build -t frontend:latest .
          cd -
          cd api-gateway
          docker build --build-arg ASSET_IMAGE=frontend:latest --build-arg ASSET_PATH=/etc/nginx/html -t $REGISTRY/xenoblast-api-gateway:$IMAGE_TAG .
          docker tag $REGISTRY/xenoblast-api-gateway:$IMAGE_TAG $REGISTRY/xenoblast-api-gateway:latest
          docker push -a $REGISTRY/xenoblast-api-gateway
          cd -
          cd backend
          docker build -t $REGISTRY/xenoblast-backend:$IMAGE_TAG .
          docker tag $REGISTRY/xenoblast-backend:$IMAGE_TAG $REGISTRY/xenoblast-backend:latest
          docker push -a $REGISTRY/xenoblast-backend
          cd -
